### ISSUE TITLE
Hexo卡哇伊插件hexo-helper-live2d

### ISSUE THREAD

**Issue by itgoyo** [itgoyo/500Days-Of-Github#44]
[hexo-helper-live2d](https://github.com/EYHN/hexo-helper-live2d)

首先安装插件代码
```
npm install --save hexo-helper-live2d@3.x
```
然后在根配置文件和主题配置文件填入一下信息
```
 Live2D
## https://github.com/EYHN/hexo-helper-live2d
ive2d:
  enable: true
  scriptFrom: jsdelivr
  model:
    use: https://cdn.jsdelivr.net/npm/live2d-widget-model-koharu@1.0.5/assets/koharu.model.json
  display:
    position: left
    width: 75
    height: 150
  mobile:
    show: true
  react:
    opacityDefault: 1
    opacityOnHover: 0.2
```
